### ISSUE TITLE
Official Gatsby plugin

### ISSUE THREAD

**Issue by mattcompiles** [cometkim/gatsby-plugin-treat#1]
Hey bud 👋,

Just became aware of this plugin today. Awesome to see people using treat in the wild 😄.

However, we were looking to launch an official gatsby plugin located in the [treat monorepo](https://github.com/seek-oss/treat/tree/master/packages/gatsby-plugin-treat). That way we can ensure it is kept up to date with the core library and is easier for users to navigate. 

Is there any chance you'd be willing to give up the package name? We'd still love to have you as a contributor to the official plugin.

**Comment by cometkim** [comment]
Hey @mattsjones 

Sounds cool that treat provides gatsby plugin officially and yes, I will give the package name :)

Actually, I was looking for something to replace linaria with some issues while maintaining [gatsby-plugin-linaria](https://github.com/silvenon/gatsby-plugin-linaria). Treat seems to be a great alternative, but I encountered a webpack issue so I couldn't use it properly. After the plugin was completed, I planned to donate to the treat community.

**Comment by mattcompiles** [comment]
Awesome news! Thanks!
My npm user is `mattsjones`. If you could just add me as admin I can sort out the rest 😄.

Is your webpack issue anything I can help with?

**Comment by cometkim** [comment]
I just invited you to the package maintainer.

> Is your webpack issue anything I can help with?

I don't think so but you can get info about issue from code: https://github.com/cometkim/gatsby-plugin-treat/blob/f3eb82c2773513b0a1ac664bd98582e1c700494f/src/gatsby-node.ts#L22-L31

- https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/162
- https://github.com/webpack-contrib/mini-css-extract-plugin/issues/73

**Comment by mattcompiles** [comment]
Hmm, not sure about that one. Try out the plugin we just released and see if you have the same issues.
